Section "ServerFlags"
  Option "DontVTSwitch" "true"
  Option "AllowMouseOpenFail" "true"
  Option "PciForceNone" "true"
  Option "AutoEnableDevices" "false"
  Option "AutoAddDevices" "false"
EndSection

Section "Device"
  Identifier "dummy_videocard"
  Driver "dummy"
  Option "ConstantDPI" "true"
  VideoRam 1024000
EndSection

Section "Monitor"
  Identifier "dummy_monitor"
  HorizSync 5.0 - 1000.0
  VertRefresh 5.0 - 200.0
  Modeline "1440x900_30.00" 54.67 1440 1472 1616 1792 900 901 904 913 -HSync +Vsync
EndSection

Section "Screen"
  Identifier "dummy_screen"
  Device "dummy_videocard"
  Monitor "dummy_monitor"
  DefaultDepth 24
  SubSection "Display"
    Viewport 0 0
    Depth 24
    Virtual 3840 2400
    Modes "1440x900_30.00"
  EndSubSection
EndSection

Section "ServerLayout"
  Identifier "dummy_layout"
  Screen "dummy_screen"
EndSection
